import type { NextPage } from 'next'
import Head from 'next/head'

import { Toaster } from 'react-hot-toast'
import ViewChat from '../components/viewChat'
import Navbar from '../components/navbar'
import 'bootstrap/dist/css/bootstrap.min.css';

const Home: NextPage = () => {
  return (
    <div className="max-w-screen-xl m-auto pb-4 md:pb-12">
      <Head>
        <title>AI Marketplace Chat Demo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Toaster />
      <Navbar />

      <h1 className="m-auto text-center md:mt-8 text-4xl md:text-4xl font-extrabold">
        <a href="https://github.com/mikeghen/ai-marketplace" target="_blank" rel="noreferrer" className="">
          AI Marketplace Chat Demo
        </a>
      </h1>

      <br/>

      <ViewChat />



      {/* <div className="flex mt-4 space-x-3">
        <div className="flex justify-center mt-8  max-w-4xl m-auto">
          <AdminPanel />
        </div>
      </div> */}


      <style jsx>{`
        .rotating-hue {
          background-image: -webkit-linear-gradient(92deg, #f35626, #feab3a);
          -webkit-background-clip: text;
          -webkit-text-fill-color: transparent;
          -webkit-animation: hue 30s infinite linear;
        }

        @-webkit-keyframes hue {
          from {
            -webkit-filter: hue-rotate(0deg);
          }
          to {
            -webkit-filter: hue-rotate(-360deg);
          }
        }
      `}</style>
    </div>
  )
}

export default Home
